# Generated by Django 4.1.7 on 2023-03-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empleado_responsable',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='producto',
        ),
    ]
